#!/bin/sh
#
# Copyright © 2018 Raptor Engineering, LLC
# Released under the GNU GPL v3

set +e

# Set OEM3 bit
/sbin/devmem-aspeed 0x1e789060 w $(printf '0x%X\n' "$((`/sbin/devmem-aspeed 0x1e789060` | 0x10))")

# Always return success
exit 0
